language: go


# S: Build Lifecycle
install:
- go get github.com/gohugoio/hugo



script:
  - git clone https://github.com/rootsongjc/beautifulhugo.git themes/beautifulhugo
  - git clone "https://${blog_token}@${GH_REF}" public
  - hugo version
  - hugo

after_script:
  - cd ./public
  - cp ../CNAME ./
  #- git init
  - git config user.name "yinlongfei"
  - git config user.email "1045438139@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${blog_token}@${GH_REF}" master:master

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/loverto/yinlongfei.com.git
